version: '3'
services:
  postgres-team-finder:
    container_name: postgres-team-finder
    image: postgis/postgis
    volumes:
      - postgres-team-finder:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: team-finder
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5431"
    ports:
      - "5431:5431"
    command: -p 5431
    restart: always

  team-finder-service:
    image: jacekg11/team-finder:latest
    pull_policy: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres-team-finder

volumes:
  postgres-team-finder:
    external: true